# Generated by Django 4.0.6 on 2022-08-06 18:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='Select', max_length=2),
            preserve_default=False,
        ),
    ]
