# Generated by Django 4.0.6 on 2022-08-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_avatar_profile_avi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avi',
            new_name='avatar',
        ),
    ]
