# Generated by Django 4.0.6 on 2022-08-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('prefer not to say', 'Prefer not to say'), ('female', 'Female'), ('others', 'Others'), ('male', 'Male')], default='prefer not to say', max_length=20),
        ),
    ]
